services:
  # Backend API service
  - type: web
    name: customer-support-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python init_db.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DATABASE_URL
        fromDatabase:
          name: customer-support-db
          property: connectionString

  # Frontend static site
  - type: web
    name: customer-support-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: customer-support-api
          type: web
          envVarKey: RENDER_EXTERNAL_URL

# Database
databases:
  - name: customer-support-db
    plan: free